### ISSUE TITLE
Fail to compile the pre-processing toolkit in dataset/process_tools.

### ISSUE THREAD

**Issue by MingfeiShiMS** [PKU-EPIC/GAPartNet#18]
Dear Haoran:

I am reproducing GAPartNet. When compiling dataset/process_tools repository, I find it is hard.

Firstly, I finish the process of "Rendering Toolkit".

Then, due to the pytorch vision limitation when installing the PointNet++ library (I install torch==1.9.0), it seems to work.

But when I compile "python convert_rendered_into_input.py" , there is a mistake:
Start: Box
Box : 800
Sampling 0/800 Box_100129_0_0
Use pointnet2_cuda!
/home/junhuan/anaconda3/envs/gadata/lib/python3.8/site-packages/torch/cuda/__init__.py:106: UserWarning: 
NVIDIA GeForce RTX 4090 with CUDA capability sm_89 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 4090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "process_tools/convert_rendered_into_input.py", line 225, in <module>
    ret = sample_and_save(fn, DATA_PATH, SAVE_PATH, NUM_POINTS, VISUALIZE)
  File "process_tools/convert_rendered_into_input.py", line 115, in sample_and_save
    pcs_sampled, fps_idx = FPS(pcs, num_points)
  File "/home/shimingfei/GAPartNet/dataset/process_tools/utils/sample_utils.py", line 66, in FPS
    fps_idx = fps_idx_tensor.cpu().numpy()[0]
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Moreover, if I use "CUDA_LAUNCH_BLOCKING=1", it does not work, only with less error descriptions in terminal:
Start: Box
Box : 800
Sampling 0/800 Box_100129_0_0
Use pointnet2_cuda!
/home/junhuan/anaconda3/envs/gadata/lib/python3.8/site-packages/torch/cuda/__init__.py:106: UserWarning: 
NVIDIA GeForce RTX 4090 with CUDA capability sm_89 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 4090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
CUDA kernel failed : an illegal memory access was encountered

I am looking forward to your reply.

Best Regards

**Comment by geng-haoran** [comment]
Hi, thanks for your interest in this work.
Have you ever tried the `demo.ipynb` in the code? You should first try that. I just ran it from scratch and everything works. I will also try the script you mentioned with an RTX 4090.

**Comment by geng-haoran** [comment]
Follow-up, I think you should use the proper version of CUDA and torch. A tested version is: CUDA 11.8 with torch 1.13.1+cu117 and runs the scripts in the README. I updated a more detailed one in README.

**Comment by MingfeiShiMS** [comment]
Thank you for your kind reply! 
I can finish demo.ipynb, but the following training, testing and manipulation stages still require the processed dataset.
And just now, I tried another pytorch:
(original): # CUDA 10.2
conda install pytorch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 cudatoolkit=10.2 -c pytorch
(corrected): # CUDA 11.3
conda install pytorch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 cudatoolkit=11.3 -c pytorch -c conda-forge
And it works. Thanks.
